title: "Bamjun's Code Sphere"
author: "bamjun"

baseurl: /blog

description: "bamjun's Coding Playground." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.


# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "khy5116@naver.com"
github_username: "bamjun"
linkedin_username: "잉쿠-아-24b78b261"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username


#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Minimal Mistakes: A flexible theme for building a personal site, blog, project documentation, or portfolio​​.
# Al-Folio: A clean and responsive theme ideal for academics​​.
# Just the Docs: Offers high customization and responsive design, specifically tailored for documentation with built-in search capabilities​​.
# Chirpy: A minimal, responsive theme designed for technical writing​​.
# Beautiful Jekyll: Allows you to build a simple and beautiful website quickly​​.
# Hyde: A two-column theme that stands out for its bold style​​.
# Minima: A one-size-fits-all theme, particularly suitable for writers​​.
# Lanyon: Features a content-first approach with a sliding sidebar​​.
# Online-CV: A minimal theme for hosting a resume or CV on GitHub with ease​​.
# Moon: A minimal, one-column theme, focusing on simplicity​​.
theme: "Minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
      
